### ISSUE TITLE
dashboard url no longer works

### ISSUE THREAD

**Issue by zhaohanson1** [tmxkn1/Microsoft-Rewards-Bot#12]
https://github.com/tmxkn1/Microsoft-Rewards-Bot/blob/259ad992ce056a5dfffa548fe0e65745eafed581/msreward/worker/dashboard/dashboard.py#L13

Leads to 404, seems like MS changed/deprecated some urls? This caused quiz tasks to be skipped.
I don't remember exactly where the old url lead, but I assume it's the rewards home page.

Also, this shares the same constant name as https://github.com/tmxkn1/Microsoft-Rewards-Bot/blob/259ad992ce056a5dfffa548fe0e65745eafed581/msreward/account/stats.py#L13

I brought up an issue https://github.com/tmxkn1/Microsoft-Rewards-Bot/issues/6#issuecomment-1092583473 so probably make this the same url

also here 
https://github.com/tmxkn1/Microsoft-Rewards-Bot/blob/259ad992ce056a5dfffa548fe0e65745eafed581/msreward/msr.py#L10
even though its not used in the file

**Comment by AnthonyZJiang** [comment]
Thanks, it has been fixed.
