### ISSUE TITLE
Sign in is failed. Unable to switch to OTC verification method. Did not find the "sign in another way" link.

### ISSUE THREAD

**Issue by Rumik** [tmxkn1/Microsoft-Rewards-Bot#15]
Hi there,

the past few days I've been seeing this error with the bot... "Sign in is failed. Unable to switch to OTC verification method. Did not find the "sign in another way" link."

Any idea of a fix?

Thanks

**Comment by ashanrath** [comment]
I had this when I first used it when I'd already used that PC to sign into that account with "remember be" enabled. Try opening the rewards site manually, then manually logging out. Run again and see if it still happens.

**Comment by Rumik** [comment]
After MUCH fiddling and re-setting up, I've got it working again :)

Thanks.
