### ISSUE TITLE
cannot find userStatus

### ISSUE THREAD

**Issue by diswag3** [tmxkn1/Microsoft-Rewards-Bot#6]
![image](https://user-images.githubusercontent.com/99859091/154408325-e8f426c4-ad07-4422-9711-3ea447dbb049.png)

**Comment by AnthonyZJiang** [comment]
Is this persistent? I sometimes see this too, but it disappears the next day or upon restart. I haven't got time to diagnose this, tbh. I assume it has something to do with some page structure changes or network issues.

**Comment by diswag3** [comment]
yeah it usually fixes upon restarting, but just was wondering what was causing it really

**Comment by charettepa** [comment]
this is consistant for me as of yesterday
regardles of the amount of restarts
could this lineup with the user agent / version now being over 99

**Comment by Rumik** [comment]
Same for me, tho I'm yet to try it today.

**Comment by zhaohanson1** [comment]
Hello all, I get also get this error and for me, it seems to be a url problem. 

In msrewards/account/stats.py, the DASHBOARD_URL is 'https://account.microsoft.com/rewards/', which leads to 404 page

Removing the backslash resolve this, that is, change the url to DASHBOARD_URL = 'https://account.microsoft.com/rewards'

**Comment by ashanrath** [comment]
> Hello all, I get also get this error and for me, it seems to be a url problem. 
> 
> In msrewards/account/stats.py, the DASHBOARD_URL is 'https://account.microsoft.com/rewards/', which leads to 404 page
> 
> Removing the backslash resolve this, that is, change the url to DASHBOARD_URL = 'https://account.microsoft.com/rewards'

Confirmed, this fixes. I'll raise a PR later today if no-one beats me to it.

**Comment by AnthonyZJiang** [comment]
Thanks, it has been fixed.
