### ISSUE TITLE
It wont do the quiz

### ISSUE THREAD

**Issue by diswag3** [tmxkn1/Microsoft-Rewards-Bot#8]
It does the searches, the dailys, even the more activities tab; but it will not do the quiz on the daily set. There is an occasional error message about UserStatus, but when i re-run the program and the UserStatus bug is fixed it still does not do the quiz

**Comment by ashanrath** [comment]
Nobody can help you unless you post the full debug logs and the associated screenshots.

**Comment by diswag3** [comment]
![image](https://user-images.githubusercontent.com/99859091/154831642-96901273-1d15-4e42-876a-336ff816c495.png)

**Comment by diswag3** [comment]
![image](https://user-images.githubusercontent.com/99859091/154831650-f49471fd-5720-494c-bacf-dcdcb56da752.png)

**Comment by ashanrath** [comment]
You still haven't attached the log text and image files.

**Comment by diswag3** [comment]
what do you mean? thats all i get in the cmd prompt and it wont do my quiz. can you further explain?

**Comment by ashanrath** [comment]
I suggest you fully read the readme file, in particular the logging
options, then look in the "logs" subdirectory inside wherever you cloned
the repo locally.
